language: python
matrix:
  include:
    - env: TOXENV=black
    - env: TOXENV=flake8
    - env: TOXENV=isort
    - env: TOXENV=py36
      python: 3.6
    - env: TOXENV=py37
      python: 3.7
    - env: TOXENV=py38
      python: 3.8
before_install:
   - sudo apt-get update
   - sudo apt-get install libgnutls28-dev
install:
  - pip install tox
script:
  - tox
